apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dagger-in-argo-
  namespace: argo
spec:
  entrypoint: dagger-workflow
  volumes:
    - name: dagger-socket
      hostPath:
        path: /var/run/dagger
  templates:
    - name: dagger-workflow
      inputs:
        artifacts:
          - name: project-source
            path: /work
            git:
              repo: https://github.com/nunofrribeiro/personal-blog.git
              singlebranch: true
              branch: "main"
              depth: 1
          - name: dagger-cli
            path: /usr/local/bin
            mode: 0755
            http:
              url: https://github.com/dagger/dagger/releases/download/v0.13.3/dagger_v0.13.3_linux_amd64.tar.gz
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["dagger call test-result"]
        workingDir: /work
        env:
        - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
          value: "unix:///var/run/dagger/buildkitd.sock"
        - name: "DAGGER_CLOUD_TOKEN"
          valueFrom:
            secretKeyRef:
              name: dagger-cloud
              key: token
        - name: "INFISICAL_SECRET"
          valueFrom:
            secretKeyRef:
              name: infisical-secret
              key: infisical_secret
        - name: "INFISICAL_ID"
          valueFrom:
            secretKeyRef:
              name: infisical-secret
              key: infisical_id
        volumeMounts:
          - mountPath: /var/run/dagger
            name: dagger-socket
