apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kcd-demo
  namespace: argo
spec:
  serviceaccountname: dagger-workflow
  entrypoint: dagger-workflow
  volumes:
    - name: dagger-socket
      hostpath:
        path: /var/run/dagger
  templates:
    - name: dagger-workflow
      inputs:
        artifacts:
          - name: project-source
            path: /blog
            git:
              repo: https://github.com/nunofrribeiro/personal-blog.git
              singlebranch: true
              branch: "kcd-porto"
              depth: 1
          - name: dagger-cli
            path: /usr/local/bin
            mode: 0755
            http:
              url: https://github.com/dagger/dagger/releases/download/v0.13.0/dagger_v0.13.1_linux_amd64.tar.gz
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        # args: ["dagger call run-all --infisical-project 495b60ca-a6c5-46e9-bc08-6e37b1d715de --infisical-client-id env:INFISICAL_ID --infisical-client-secret env:INFISICAL_SECRET"]
        args: [dagger call lint]
        workingDir: /blog
        env:
        - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
          value: "unix:///var/run/dagger/buildkitd.sock"
        - name: "DAGGER_CLOUD_TOKEN"
          valueFrom:
            secretKeyRef:
              name: dagger-cloud
              key: token
        - name: "INFISICAL_SECRET"
          valueFrom:
            secretKeyRef:
              name: infisical-secret
              key: infisical_secret
        - name: "INFISICAL_ID"
          valueFrom:
            secretKeyRef:
              name: infisical-secret
              key: infisical_id
        volumeMounts:
          - mountPath: /var/run/dagger
            name: dagger-socket
