apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kcd-demo
  namespace: argo
spec:
  serviceAccountName: dagger-workflow
  entrypoint: dagger-workflow
  volumes:
    - name: dagger-socket
      hostPath:
        path: /var/run/dagger
  templates:
    - name: dagger-workflow
      inputs:
        artifacts:
          - name: project-source
            path: /blog
            git:
              repo: https://github.com/NunoFrRibeiro/personal-blog.git
              singleBranch: true
              branch: "kcd-porto"
              depth: 1
          - name: dagger-cli
            path: /usr/local/bin
            mode: 0755
            http:
              url: https://github.com/dagger/dagger/releases/download/v0.13.0/dagger_v0.13.0_linux_amd64.tar.gz
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args: ["dagger call --source . lint"]
        workingDir: /blog
        env:
        - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
          value: "unix:///var/run/dagger/buildkitd.sock"
        - name: "DAGGER_CLOUD_TOKEN"
          valueFrom:
            secretKeyRef:
              name: dagger-cloud
              key: token
        volumeMounts:
          - mountPath: /var/run/dagger
            name: dagger-socket
