name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/*'
    branches: [main]

env:
  DAGGER_VERSION: 0.13.3

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run module Run-All
        uses: dagger/dagger-for-github@29a88e72255e732147ba18a670978b90bcc59efd # v6.4.0  
        with:
          verb: call
          args:  --ref ${{ github.ref }} run-all --infisical-project 495b60ca-a6c5-46e9-bc08-6e37b1d715de --infisical-client-id env:INFISICAL_CLIENT_ID --infisical-client-secret env:INFISICAL_CLIENT_SECRET
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: ${{ env.DAGGER_VERSION }}
        env:
          INFISICAL_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_SCRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
